#SpringBoot properties

spring.application.name=ssnqb
server.port=8080


#clamAV properties

clamav.host=localhost
clamav.port=3310
clamav.timeout=5000
clamav.stream.maxlength=20480


#Feedback Messages

document.scan.clamav.failed=An Error occured. Impossible to scan your file 
document.scan.clamav.virus=Your file is suspected to be inspected
